name: Recipe Storage build workflow


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch all history for linting
      - name: Run commit lint
        uses: wagoid/commitlint-github-action@v6

  code-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python with uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: make deps
      - name: Run code lint
        run: make lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python with uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: make deps
      - name: Run unit tests
        run: make test

  code-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload results to the Security tab
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
